wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.9
    start_time: 1672875299.386294
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.13.7
      8:
      - 2
      - 4
      - 5
batch_size:
  desc: null
  value: 64
cutmix_alpha:
  desc: null
  value: 1.0
cutmix_prob:
  desc: null
  value: 0.8
data_dir:
  desc: null
  value: images
image_shape:
  desc: null
  value:
  - 50
  - 50
label_smoothing:
  desc: null
  value: 0.1
logging_rate:
  desc: null
  value: 1000
lr:
  desc: null
  value: 0.01
mixup_alpha:
  desc: null
  value: 0.3
model_name:
  desc: null
  value: duck-sheep
momentum:
  desc: null
  value: 0.9
num_classes:
  desc: null
  value: 2
num_epochs:
  desc: null
  value: 10
optimizer:
  desc: null
  value: Adam
patience_length:
  desc: null
  value: 3
patience_threshold:
  desc: null
  value: 0.95
resize_scale:
  desc: null
  value:
  - 0.2
  - 1.0
save_checkpoints:
  desc: null
  value: false
test_batch_size:
  desc: null
  value: 128
test_size:
  desc: null
  value: 0.2
